-- Public contact requests are write-only for visitors. Editorial content and
-- customer requests can be read or managed only by an active MYNORA admin.

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null default '',
  content text not null,
  cover_image_path text,
  status text not null default 'draft' check (status in ('draft', 'review', 'published', 'archived')),
  seo_title text not null default '',
  seo_description text not null default '',
  author_email text,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint posts_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint posts_title_not_blank check (char_length(btrim(title)) between 1 and 180),
  constraint posts_content_not_blank check (char_length(btrim(content)) > 0),
  constraint posts_published_at_matches_status check (
    (status = 'published' and published_at is not null)
    or (status <> 'published' and published_at is null)
  )
);

create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  phone text,
  subject text not null default '',
  message text not null,
  status text not null default 'new' check (status in ('new', 'in_progress', 'responded', 'closed', 'spam')),
  source text not null default 'website' check (source in ('website', 'manual')),
  internal_note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contact_submissions_name_not_blank check (char_length(btrim(name)) between 2 and 120),
  constraint contact_submissions_message_not_blank check (char_length(btrim(message)) between 5 and 5000),
  constraint contact_submissions_reply_channel check (
    nullif(btrim(coalesce(email, '')), '') is not null
    or nullif(btrim(coalesce(phone, '')), '') is not null
  ),
  constraint contact_submissions_email_length check (email is null or char_length(email) <= 254),
  constraint contact_submissions_phone_length check (phone is null or char_length(phone) <= 40),
  constraint contact_submissions_subject_length check (char_length(subject) <= 180)
);

alter table public.posts enable row level security;
alter table public.contact_submissions enable row level security;

revoke all on table public.posts from anon, authenticated;
revoke all on table public.contact_submissions from anon, authenticated;

grant usage on schema public to anon, authenticated, service_role;
grant select on table public.posts to anon, authenticated;
grant insert, update on table public.posts to authenticated;
grant insert on table public.contact_submissions to anon, authenticated;
grant select, update on table public.contact_submissions to authenticated;
grant all privileges on table public.posts, public.contact_submissions to service_role;
grant usage on sequence public.posts_id_seq to authenticated, service_role;
grant usage on sequence public.contact_submissions_id_seq to anon, authenticated, service_role;

create index if not exists posts_published_at_idx
  on public.posts (published_at desc)
  where status = 'published';

create index if not exists contact_submissions_created_at_idx
  on public.contact_submissions (created_at desc);

create index if not exists contact_submissions_status_created_at_idx
  on public.contact_submissions (status, created_at desc);

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'posts' and policyname = 'Published posts are public') then
    create policy "Published posts are public"
      on public.posts for select to anon, authenticated
      using (status = 'published' and published_at <= now());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'posts' and policyname = 'Active admins manage posts') then
    create policy "Active admins manage posts"
      on public.posts for all to authenticated
      using (
        exists (
          select 1 from public.admin_users
          where email = ((select auth.jwt()) ->> 'email') and is_active
        )
      )
      with check (
        exists (
          select 1 from public.admin_users
          where email = ((select auth.jwt()) ->> 'email') and is_active
        )
      );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'contact_submissions' and policyname = 'Visitors create contact submissions') then
    create policy "Visitors create contact submissions"
      on public.contact_submissions for insert to anon, authenticated
      with check (
        status = 'new'
        and source = 'website'
        and internal_note = ''
      );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'contact_submissions' and policyname = 'Active admins manage contact submissions') then
    create policy "Active admins manage contact submissions"
      on public.contact_submissions for all to authenticated
      using (
        exists (
          select 1 from public.admin_users
          where email = ((select auth.jwt()) ->> 'email') and is_active
        )
      )
      with check (
        exists (
          select 1 from public.admin_users
          where email = ((select auth.jwt()) ->> 'email') and is_active
        )
      );
  end if;
end
$$;
